"""API router bootstrap for the standalone data service."""

from fastapi import APIRouter

from .v1 import router as v1_router
from .v1.code_assets_devwiki import router as code_assets_devwiki_target_router
from .v1.code_assets_graph import router as code_assets_graph_target_router
from .v1.code_assets_quality import router as code_assets_quality_target_router
from .v1.code_assets_architecture import router as code_assets_architecture_target_router
from .v1.code_assets_doc_grounded_architecture import router as code_assets_doc_grounded_architecture_target_router
from .v1.code_assets_architecture_intent import router as code_assets_architecture_intent_target_router
from .v1.code_assets_coding_agent import router as code_assets_coding_agent_target_router
from .v1.code_assets_platform import router as code_assets_platform_target_router
from .v1.code_assets_agent_productization import router as code_assets_agent_productization_target_router
from .v1.code_assets_human_agent_deepening import router as code_assets_human_agent_deepening_target_router
from .v1.code_assets_stabilization_e2e_portal import router as code_assets_stabilization_e2e_portal_target_router
from .v1.code_assets_external_e2e_portal_delivery import router as code_assets_external_e2e_portal_delivery_target_router
from .v1.code_assets_agent_memory_release import router as code_assets_agent_memory_release_target_router
from .v1.code_assets_project_acceptance_hardening import router as code_assets_project_acceptance_hardening_target_router
from .v1.code_assets_real_document_acceptance import router as code_assets_real_document_acceptance_target_router
from .v1.code_assets_real_document_full_corpus_release import router as code_assets_real_document_full_corpus_release_target_router
from .v1.code_assets_real_acceptance_closure import router as code_assets_real_acceptance_closure_target_router
from .v1.code_assets_automated_evidence_closure import router as code_assets_automated_evidence_closure_target_router
from .v1.workspace_portfolio import router as workspace_portfolio_target_router
from .v1.code_assets import router as code_assets_target_router
from .v1.data_service import target_router as data_service_target_router
from .v1.research_notebook import provider_router as research_notebook_provider_router
from .v1.research_notebook import router as research_notebook_target_router

api_router = APIRouter()
api_router.include_router(data_service_target_router)
api_router.include_router(code_assets_target_router)
api_router.include_router(code_assets_devwiki_target_router)
api_router.include_router(code_assets_graph_target_router)
api_router.include_router(code_assets_quality_target_router)
api_router.include_router(code_assets_architecture_target_router)
api_router.include_router(code_assets_doc_grounded_architecture_target_router)
api_router.include_router(code_assets_architecture_intent_target_router)
api_router.include_router(code_assets_coding_agent_target_router)
api_router.include_router(code_assets_platform_target_router)
api_router.include_router(code_assets_agent_productization_target_router)
api_router.include_router(code_assets_human_agent_deepening_target_router)
api_router.include_router(code_assets_stabilization_e2e_portal_target_router)
api_router.include_router(code_assets_external_e2e_portal_delivery_target_router)
api_router.include_router(code_assets_agent_memory_release_target_router)
api_router.include_router(code_assets_project_acceptance_hardening_target_router)
api_router.include_router(code_assets_real_document_acceptance_target_router)
api_router.include_router(code_assets_real_document_full_corpus_release_target_router)
api_router.include_router(code_assets_real_acceptance_closure_target_router)
api_router.include_router(code_assets_automated_evidence_closure_target_router)
api_router.include_router(workspace_portfolio_target_router)
api_router.include_router(research_notebook_target_router)
api_router.include_router(research_notebook_provider_router)
api_router.include_router(v1_router, prefix="/v1")

__all__ = ["api_router"]
